### PR TITLE
fix Unable to parse the pyproject.toml file. #156

### PR DESCRIPTION
**Pull request by vipcxj**

### CODE REVIEW

**Comment by dmerejkowsky** [comment]
Thanks for the bug fix :)

**Comment by dmerejkowsky** [comment]
Hum. All tests are failing. This needs some investigation ...

**Comment by vipcxj** [comment]
@dmerejkowsky All test are passed now.
I'm not sure it's a perfect fix, though, because tomlkit's unwrap still looks unreliable, and some deep data may not be unwrapped properly, but it's more reliable than before

**Comment by vipcxj** [comment]
@dmerejkowsky lints are passed, including something not I changed.

**Comment by vipcxj** [comment]
@dmerejkowsky Could you approve running workflows?

**Comment by dmerejkowsky** [comment]
Done and merged. Thanks for the bug fix

**Comment by vipcxj** [comment]
@dmerejkowsky when is the new version released? Currently I have to install from the source code.

**Pull request merged**
